apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jvminfo
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: argocd
    repoURL: https://github.com/celeguim/k3s-rpi-project.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
