apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jvminfo
  name: jvminfo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jvminfo
  type: LoadBalancer
status:
  loadBalancer: {}
