apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jvminfo
  name: jvminfo
spec:
  replicas: 30
  selector:
    matchLabels:
      app: jvminfo
  template:
    metadata:
      labels:
        app: jvminfo
    spec:
      containers:
      - image: celeguim/jvminfo:latest
        name: jvminfo
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
