---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  annotations:
    nginx.org/proxy-connect-timeout: "10s"
    nginx.org/proxy-read-timeout: "10s"
    nginx.org/lb-method: "round_robin"
spec:
  ingressClassName: nginx
  rules:
    - host: ingress.nginx.example.com
      http:
        paths:
          - path: /jvminfo
            pathType: Prefix
            backend:
              service:
                name: jvminfo
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
